### ISSUE TITLE
Precompiled package

### ISSUE THREAD

**Issue by aXe1** [neurocyte/android-haskell-activity#1]
Could you publish a precompiled APK to play with? I failed building ghc-android yet and just want to examine resulting package. Also, what is the minimum Android version required?
If it's possible, please, publish version targeting Android 2.2.
Thank you.

**Comment by neurocyte** [comment]
I’m not sure there is any point in that. It’s a pretty trivial example. Just one Java class file and a Haskell shared object file. I would rather spend some time getting pre-built cross-compilers built.

**Comment by aXe1** [comment]
Just now compiling Haskell shared object is tricky.. I just want to have understanding how fat APK will be with all Haskell staff packed inside. Also it is interesting, if there would be sensible performance penalty, but for that Hello World isn't enough of course. For comparison - AFAIK Mono for Android is a similar thing and it adds ~3 Mb of libs and doesn't give sensible performance penalty.
Can you comment on Haskell for Android?

**Comment by neurocyte** [comment]
The apk for android-haskell-activity is around 3Mb. I haven’t looked at reducing it yet. It may be possible though. I doubt a full haskell application would be much bigger. Most of the size is the base libraries and the RTS, which is huge compared to any actual application.

**Comment by gliptak** [comment]
Neurocyte, how is `libhaskell.so` generated? From https://github.com/neurocyte/ghc-android? Thanks

**Comment by neurocyte** [comment]
Yes. libhaskell.so is built by arm-linux-androideabi-cabal and/or i686-linux-android-cabal. See custom_rules.xml. These are wrapper scripts around cabal for calling the cross-compiler correctly. They are installed by the cross-compiler build script in ghc-android.
