### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by amulcahy** [neurocyte/android-haskell-activity#4]
Thanks very much for providing the ghc-android tool and foreign-jni package.  I've made a small demo Haskell Android app (https://github.com/amulcahy/LambdaMC) based on your android-haskell-activity.

Would it be ok if I include the attribution line below in the app's "ABOUT" screen or would you prefer that I don't:

 "Based on the example at https://github.com/neurocyte/android-haskell-activity"

I included the above line in the README file on GitHub, but I wanted to ask your opinion about the app before releasing it on Google Play.

Anthony Mulcahy

**Comment by davidrusu** [comment]
OMG a real live haskell app on the play store?!?!! That is so awesome. Great work :+1:

**Comment by neurocyte** [comment]
You don’t _have_ to give attribution, but you sure are _allowed_ to yes!
